name: Android Build

on:
  push:
    branches: [ main ] # Trigger on pushes to the main branch
  workflow_dispatch:  # Add this line to enable manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Create Git Tag
        id: tag
        run: |
          git tag v0.1.${{ github.run_number }}
          git push origin v0.1.${{ github.run_number }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: v0.1.${{ github.run_number }}
