name: Android Release

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
  workflow_dispatch:  # Add this line to enable manual triggering

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    env:
      TAG_NAME: v0.1.${{ github.run_number }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Release APK
        uses: gradle/actions/setup-gradle@v3

      - name: Assemble the project
        run: ./gradlew assemble

      - name: Checks
        run: find . -type f -name "*.apk"

      - name: Create Git Tag
        id: tag
        run: |
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}

      - name: Sign app APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.KEY_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASS }}
          keyPassword: ${{ secrets.KEYSTORE_PASS }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        id: publish_release
        with:
          files: ${{steps.sign_app.outputs.signedReleaseFile}}
          draft: false
          prerelease: true
          tag_name: ${{ env.TAG_NAME }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Signed APK
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
